#!/usr/bin/env bash
# =============================================================================
# 06_export_23andme.sh — (optional) extract the ~640k 23andMe chip positions
# from the personal VCF into a 23andMe-style raw genotype text file, suitable
# for direct comparison or upload to third-party interpreters (Genomelink,
# SelfDecode, Promethease).
#
# In:  $RESULTS_DIR/$SAMPLE.vcf.gz, $CHIP_BED (23andMe v5 positions)
# Out: $RESULTS_DIR/$SAMPLE.23andme.txt
# =============================================================================
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
stage_banner "06 export 23andMe format"

if [[ "${RUN_23ANDME}" != "true" ]]; then
  log_ok "RUN_23ANDME=${RUN_23ANDME}; skipping 23andMe export."
  exit 0
fi

IN_VCF="${RESULTS_DIR}/${SAMPLE}.vcf.gz"
OUT_TXT="${RESULTS_DIR}/${SAMPLE}.23andme.txt"

if skip_if_done "${OUT_TXT}"; then exit 0; fi

require bcftools awk
require_file "${IN_VCF}" "personal VCF (run stage 03)"

# The chip BED is not bundled (see stage 00). If it's absent, skip gracefully.
if [[ ! -s "${CHIP_BED}" ]]; then
  log_warn "chip positions not found at ${CHIP_BED}; skipping 23andMe export."
  log_warn "Provide the ~640k-position BED (chrom<TAB>start<TAB>end<TAB>rsID) and re-run."
  exit 0
fi

ensure_dir "${RESULTS_DIR}"

log "extracting chip positions and formatting as 23andMe raw genotype file…"
if [[ "${DRY_RUN}" == "1" ]]; then
  echo "${_C_DIM}$(_ts)${_C_RESET} ${_C_YEL}[DRY ]${_C_RESET}  build ${OUT_TXT}" >&2
else
  {
    echo "# This data file generated by the DIY genetics pipeline from raw WGS."
    echo "# Format: rsid  chromosome  position  genotype   (23andMe-style, tab-separated)"
    echo "# Positions restricted to the 23andMe v5 chip set. Absent/no-call sites omitted."
    printf 'rsid\tchromosome\tposition\tgenotype\n'
    # Restrict the VCF to chip positions, then emit rsID / chrom / pos / GT bases.
    # bcftools query builds the two-allele genotype string from GT + REF/ALT.
    bcftools view -R "${CHIP_BED}" "${IN_VCF}" -Ou 2>/dev/null \
      | bcftools query -f '%ID\t%CHROM\t%POS\t[%TGT]\n' \
      | awk -F'\t' '{
          gsub(/chr/, "", $2);          # 23andMe uses bare chrom names
          gt=$4; gsub(/[|/]/, "", gt);  # A|G -> AG ; drop phasing
          if (gt=="" || gt==".." || gt==".") next;
          rsid=($1=="." ? $2"_"$3 : $1);
          printf "%s\t%s\t%s\t%s\n", rsid, $2, $3, gt;
        }'
  } > "${OUT_TXT}"
fi

log_ok "23andMe-format export: ${OUT_TXT}"
log "Upload to a third-party interpreter (Genomelink/SelfDecode/Promethease) or diff against a real export."
