#!/usr/bin/env bash
# =============================================================================
# 06_export_23andme.sh — (optional) export the personal VCF as a 23andMe-style
# raw genotype file, restricted to the chip's SNP set — matched by rsID.
#
# rsID-based (not position-based) so it is BUILD-AGNOSTIC: a 23andMe raw export
# is build 37 while this pipeline is GRCh38, but rsIDs are stable across builds.
# The personal VCF is first annotated with dbSNP rsIDs, then filtered to the
# chip rsID list.
#
# In:  $RESULTS_DIR/$SAMPLE.vcf.gz, $DBSNP_VCF, $CHIP_RSIDS (rsIDs, one per line)
# Out: $RESULTS_DIR/$SAMPLE.23andme.txt
# =============================================================================
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
stage_banner "06 export 23andMe format"

if [[ "${RUN_23ANDME}" != "true" ]]; then
  log_ok "RUN_23ANDME=${RUN_23ANDME}; skipping 23andMe export."
  exit 0
fi

IN_VCF="${RESULTS_DIR}/${SAMPLE}.vcf.gz"
ANNOT_VCF="${RESULTS_DIR}/${SAMPLE}.rsid.vcf.gz"
OUT_TXT="${RESULTS_DIR}/${SAMPLE}.23andme.txt"

if skip_if_done "${OUT_TXT}"; then exit 0; fi

require bcftools awk tabix
require_file "${IN_VCF}" "personal VCF (run stage 03)"

# The chip rsID list is not bundled (23andMe's manifest isn't publicly licensed).
# Accept any file whose first whitespace-delimited token per line is an rsID —
# e.g. a 23andMe raw export (rsid<TAB>chrom<TAB>pos<TAB>genotype) works directly.
if [[ ! -s "${CHIP_RSIDS}" ]]; then
  log_warn "chip rsID list not found at ${CHIP_RSIDS}; skipping 23andMe export."
  log_warn "Provide a file of rsIDs (one 'rs...' per line, or a 23andMe raw export)."
  exit 0
fi
require_file "${DBSNP_VCF}" "dbSNP (needed to annotate rsIDs; run stage 00)"
ensure_dir "${RESULTS_DIR}"

# ---- 1. annotate the personal VCF with dbSNP rsIDs -------------------------
if ! skip_if_done "${ANNOT_VCF}"; then
  log "annotating personal VCF with dbSNP rsIDs (merge against known-sites)…"
  run bash -c "bcftools annotate -a '${DBSNP_VCF}' -c ID '${IN_VCF}' -Oz -o '${ANNOT_VCF}' && tabix -f -p vcf '${ANNOT_VCF}'"
fi

# ---- 2. filter to the chip rsIDs, emit 23andMe format ----------------------
log "extracting chip rsIDs and formatting as a 23andMe raw genotype file…"
if [[ "${DRY_RUN}" == "1" ]]; then
  echo "${_C_DIM}$(_ts)${_C_RESET} ${_C_YEL}[DRY ]${_C_RESET}  build ${OUT_TXT}" >&2
else
  {
    echo "# Generated by the DIY genetics pipeline from raw WGS (GRCh38)."
    echo "# Restricted to the chip's rsID set; matched by rsID (build-agnostic)."
    echo "# Absent / no-call sites are omitted."
    printf 'rsid\tchromosome\tposition\tgenotype\n'
    bcftools query -f '%ID\t%CHROM\t%POS\t[%TGT]\n' "${ANNOT_VCF}" \
      | awk -F'\t' -v rsfile="${CHIP_RSIDS}" '
          BEGIN {
            while ((getline line < rsfile) > 0) {
              sub(/[ \t\r].*/, "", line)     # keep first token (the rsID)
              if (line ~ /^rs[0-9]+$/) keep[line] = 1
            }
          }
          ($1 in keep) {
            chrom = $2; sub(/^chr/, "", chrom)   # 23andMe uses bare chrom names
            gt = $4; gsub(/[|/]/, "", gt)        # A|G -> AG; drop phasing
            if (gt == "" || gt == "." || gt == "..") next
            printf "%s\t%s\t%s\t%s\n", $1, chrom, $3, gt
          }'
  } > "${OUT_TXT}"
  log_ok "exported $(( $(grep -c . "${OUT_TXT}") - 4 )) chip SNPs"
fi

log_ok "23andMe-format export: ${OUT_TXT}"
log "Upload to a third-party interpreter (Genomelink/SelfDecode/Promethease) or diff against a real export."
